### PR TITLE
feat: lightmapper

### PR DESCRIPTION
**Pull request by hm-de-paoli**

### CODE REVIEW

**Comment by michaeleggers** [comment]
Just tried it out on my Mac. Installs and runs well! 💯 
How was the OBJ created? When I open it in Blender it seems like it is defined in a right handed, y up coordinate frame? We use a right handed z-up coordinate system. That might be important when creating the UVs for the lightmap?

**Comment by hm-de-paoli** [comment]
> How was the OBJ created?

I used the createPolySoup method for that. And yes, in the lightmapper, I think I convert them back to Z-up anyway. But is that not the expected behavior of the map parser?

> That might be important when creating the UVs for the lightmap?

For the lightmaps, I don’t think it matters since the UVs are mapped to the indices. But I agree—it’s best to keep things consistent. There are parts of the lightmapper where the two coordinate systems are used somewhat interchangeably. I’ll review and tidy this up as needed. So, I can expect the OBJ file to be Z-up?

**Comment by michaeleggers** [comment]
> So, I can expect the OBJ file to be Z-up?

Yup, that should be the case. Another reason we do this is because if we model stuff in Blender we don't have to do weird conversions between coordinate systems. I had to debug the animation system for a day once 🤣 .

Also, I just realized that the obj output of `polysoup` is quite limited right now, so you won't get texture names or surface flags with it. I suggest I write a new function that outputs the polygons as a binary format. That would be easier to write (and read) and it is easy to change the data layoutl, if necessary.

> I’ll review and tidy this up as needed.

Thank you!

**Comment by michaeleggers** [comment]
Closed for #21

**Pull request closed without merging**
