### PR TITLE
feat: initial audio implementation

### LINKED ISSUE #44: Initial audio implementation
Integrate `SoLoud` into the game engine and set-up the necessary structure for the audio subsystem.

Required functionality:
- 2d audio support (e.g. ambience / soundtrack)
- 3d audio support for positional audio sources (e.g. torches, enemies, ...)
- connection to system / entity events (e.g. shooting, footsteps, UI clicks, ...)

Nice to have and other ideas (probably for later, if at all):
- sound randomization (e.g. multiple samples, pitch/ volume/speed/effect modulation, ...)
- procedural sounds for sounds with dynamic length (e.g. doors, moving platforms, ...)
- spacial sound features (rooms, obstruction / occlusion, attenuation, apply different effects to a sound (e.g. gunshot) based on environment)
- game state for sounds (e.g. idle/explore vs. combat mode), also transitions between sounds/music (just crossfade?)
- maybe even music matched effects (e.g. idle to combat transition, timed shots/explosions, etc.), probably needs beat information (bpm, etc. ?) of soundtrack files

### PR DESCRIPTION
**Pull request by Cameramorphic**
Closes #44

### CODE REVIEW

**Review by michaeleggers — COMMENTED** [review]
Nice! Works great on Linux/Windows.
I ported the audio code from the Player entity to the FirstPersonPlayer entity.
The Player entity is actually deprecated. We could throw it out. I added some comments but didn't change any of your code. Could you have a look at the first person player class? I stop the audio before checking if the handle is valid. Is that OK to do? Thanks!

**Comment by Cameramorphic** [comment]
> Nice! Works great on Linux/Windows. I ported the audio code from the Player entity to the FirstPersonPlayer entity. The Player entity is actually deprecated. We could throw it out. I added some comments but didn't change any of your code. Could you have a look at the first person player class? I stop the audio before checking if the handle is valid. Is that OK to do? Thanks!

Looks good! In general, any operation on an invalid sound handle has no effect, so this is fine.

I noticed that you applied the formatter rules to `soloud.h`, I think we should **not** do this for anything in `dependencies` to make own changes more obvious and avoid unnecessary diffs compared to the libraries' sources.

**Comment by michaeleggers** [comment]
> I noticed that you applied the formatter rules to `soloud.h`, I think we should **not** do this for anything in `dependencies` to make own changes more obvious and avoid unnecessary diffs compared to the libraries' sources.

You're right! I had to change the code in `soloud.h` (because of the `Windows.h` `#define` problem that pollutes the namespace. Is there a way to exclude the dependencies dir from `.clang-format`?

**Comment by michaeleggers** [comment]
Update regarding `.clang-format-ignore`: https://github.com/llvm/llvm-project/issues/108337

So I don't think there is anything I can do about it at the moment?

I disabled clang-format manually and then updated `soloud.h` to both the original formatting and my `#include <windows.h>` fix.

**Review by michaeleggers — APPROVED** [review]

**Pull request merged**
