### PR TITLE
feat: basic linting and building in ci

### PR DESCRIPTION
**Pull request by benekoehler**

### CODE REVIEW

**Comment by michaeleggers** [comment]
Thanks! Automatic builds are great. However, I cannot merge this with all the linting in place, as discussed before. Looking throug this it also changes *boomer style for-loops* to iterator based loops using `auto`. I discourage the use of `auto` because it is easy to write but harder to read. Also, I would prefer to stay away from iterators if a boomer style for loop can provide the same functionality. Sometimes, iterators make sense when you deal with STL's `<algorithm>`s . I use it once in `polysoup` because it initally was an offline tool from a previous project. Offline tools can be more bloated imo, the game itself should be as tight as possible.
Many files have been changed and I want to look at each carefully. Atm, I don't have the time to make a new mental map about the codebase. I suggest we take a step back after Oct. 31st, when the game is running, and carefully take on linting as its own task. I really don't  want to do deal with this right now.

**Comment by benekoehler** [comment]
i would really like to have linting in place before the end of october and i see no problem with it. the rule that changed the auto can be removed as fast as it was added :)
could you explain a bit further why you discourage `auto` that much? i find it quite handy for example when casting right afterwards. eg: `auto x = (superLongTypeWhateverItIs *)y;` 

i see it could be irritating in the for loop, but i come from a place where i want to let the compiler handle as much typing as possible. being to strict about the typings let's you introduce another set of bugs that could be handled automatically by the tooling.

**Comment by benekoehler** [comment]
i reverted the iterator stuff :) 

if you disable the whitespace highlighting in github or your editor while reviewing it makes this much easier to parse :)

**Comment by michaeleggers** [comment]
> i find it quite handy for example when casting right afterwards. eg: `auto x = (superLongTypeWhateverItIs *)y;`

This seems reasonable. I rarely come into this situation, though, where I have `superLongTypeWhateverItIs` apart from when I use "modern C++" (which I don't) or a library such as Eigen that has `everything::scoped::to::the::tiniest::instance<andOnTop::isA::template::makeHell<this::is::dumb>(hell)>` . You get the idea ;)

There are more changes the linter did I am also not fond of and I am not going to discuss them right now.

> i would really like to have linting in place before the end of october and i see no problem with it.

I do get why linting can be useful but I also don't want to see a wall of changes that do not contribute anything meaningful after I spent a day of programming. As I said, we can all get together after Oct. 31st and discuss the linter's settings so that it works in favor of all of us. If you're not comfortable with that decision or willing to accept it I am sorry, I am not going to change my mind about it. 
I am getting strong Uncle Bob 'Clean Code' vibes here. Getting lost in 'the beauty of code'.
And I have not spent a lot of time - way longer before this course started - programming in Quake(2) and thinking about game related code just to now argue with someone about this. At this point I'd rather not have you to touch
any code and focus on game design - something we already have changed because we all agree that working
on something one doesn't 'feel' is not motivating.

I have fought very long for this project to happen as part of a course and I am not willing
to get this derailed.

**Pull request closed without merging**
